export const ERROR_CODES = {
  // Common auth and validation
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  INVALID_CREDENTIALS_FORMAT: "INVALID_CREDENTIALS_FORMAT",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_VALIDATION_FAILED: "TOKEN_VALIDATION_FAILED",

  // Fixture
  INVALID_ROUND: "INVALID_ROUND",
  FIXTURE_ROUND_NOT_FOUND: "FIXTURE_ROUND_NOT_FOUND",
  INVALID_TEAM_NAME: "INVALID_TEAM_NAME",
  INVALID_FIXTURE_STATUS: "INVALID_FIXTURE_STATUS",
  FIXTURE_STATUS_NOT_FOUND: "FIXTURE_STATUS_NOT_FOUND",
  FIXTURE_DATE_NOT_FOUND: "FIXTURE_DATE_NOT_FOUND",
  PROMIEDOS_UPSTREAM_PARSE: "PROMIEDOS_UPSTREAM_PARSE",
  PROMIEDOS_UPSTREAM_SCHEMA: "PROMIEDOS_UPSTREAM_SCHEMA",
  PROMIEDOS_UPSTREAM_UNAVAILABLE: "PROMIEDOS_UPSTREAM_UNAVAILABLE",

  // Prediction
  INVALID_PREDICTION_POSITION: "INVALID_PREDICTION_POSITION",
  INVALID_PREDICTION_TEAM_NAME: "INVALID_PREDICTION_TEAM_NAME",
  INVALID_PREDICTION_CLASSIFICATION: "INVALID_PREDICTION_CLASSIFICATION",

  // Auth domain
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
